export { default as BaseCoverLetterTemplate } from './BaseCoverLetterTemplate';
export { default as ClassicLetter } from './ClassicLetter';
export { default as ProfessionalBlueLetterhead } from './ProfessionalBlueLetterhead';
export { default as CleanModernHeader } from './CleanModernHeader';
export { default as DarkHeaderCorporate } from './DarkHeaderCorporate';
export { default as MinimalWideNameHeader } from './MinimalWideNameHeader';
export { default as PlainReSubject } from './PlainReSubject';
export { default as PremiumElegantBusiness } from './PremiumElegantBusiness';
export { default as SimpleEverydayFormal } from './SimpleEverydayFormal';
