import crypto from 'node:crypto';
import OpenAI from 'openai';
import pool from '../config/db.js';
const openai = process.env.OPENAI_API_KEY ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY }) : null;
const embeddingModel = process.env.AI_LAB_EMBEDDING_MODEL || 'text-embedding-3-small';
const chatModel = process.env.AI_LAB_CHAT_MODEL || process.env.OPENAI_MODEL || 'gpt-4o-mini';
export const pipelines = { career: ['Document upload','Parser','Chunker','Embedding / index','Retrieval','Grounded CV or cover-letter generation','Citation and quality check'], education: ['Document upload','Parser','Chunker','Embedding / index','Retrieval','Grounded learner answer','Citation and safety check'] };
export const agents = { career: ['Profile analyst','Job-description analyst','CV planner','Writing agent','Quality-review agent','Export service'], education: ['Intent agent','Retrieval agent','Lesson planner agent','Quiz generator agent','Safety / quality evaluator','Narration and delivery'] };
export function chunkText(text, size = 1200, overlap = 160) { const value = String(text || '').replace(/\r\n/g,'\n').replace(/[ \t]+/g,' ').trim(); const chunks=[]; for (let start=0; start<value.length; start += Math.max(1,size-overlap)) { const chunk=value.slice(start,start+size).trim(); if(chunk) chunks.push(chunk); if(start+size>=value.length) break; } return chunks; }
export function cosineSimilarity(a,b) { if(!Array.isArray(a)||!Array.isArray(b)||a.length!==b.length) return 0; let dot=0,aa=0,bb=0; for(let i=0;i<a.length;i+=1){dot+=a[i]*b[i];aa+=a[i]**2;bb+=b[i]**2;} return aa&&bb?dot/(Math.sqrt(aa)*Math.sqrt(bb)):0; }
async function embed(input) { if(!openai) throw new Error('AI_LAB_NOT_CONFIGURED'); const result=await openai.embeddings.create({model:embeddingModel,input}); return result.data.map(item=>item.embedding); }
function id(){return crypto.randomUUID();}
export async function indexDocument({sessionId,filename,mimeType,mode,text,consentToProcess}) { if(consentToProcess!==true) throw new Error('PROCESSING_CONSENT_REQUIRED'); const content=String(text||'').slice(0,120000).trim(); if(!content) throw new Error('Document text is empty'); const chunks=chunkText(content); const vectors=await embed(chunks); const documentId=id(); const client=await pool.connect(); try { await client.query('BEGIN'); await client.query('INSERT INTO ai_lab_documents (id,session_id,source_type,filename,mime_type,content) VALUES ($1,$2,$3,$4,$5,$6)',[documentId,sessionId,mode==='career'?'career':'education',String(filename||'document.txt').slice(0,180),mimeType||'text/plain',content]); for(let i=0;i<chunks.length;i+=1) await client.query('INSERT INTO ai_lab_chunks (id,document_id,session_id,chunk_index,content,embedding) VALUES ($1,$2,$3,$4,$5,$6)',[id(),documentId,sessionId,i,chunks[i],JSON.stringify(vectors[i])]); await client.query('COMMIT'); } catch(error){await client.query('ROLLBACK');throw error;} finally{client.release();} return {documentId,filename:String(filename||'document.txt'),chunks:chunks.length}; }
export async function retrieve(sessionId,question) { const [queryVector]=await embed([String(question).slice(0,4000)]); const result=await pool.query('SELECT c.id,c.content,c.chunk_index,c.embedding,d.filename FROM ai_lab_chunks c JOIN ai_lab_documents d ON d.id=c.document_id WHERE c.session_id=$1 AND d.expires_at>now() ORDER BY c.created_at DESC LIMIT 2000',[sessionId]); return result.rows.map(row=>({id:row.id,content:row.content,chunkIndex:row.chunk_index,filename:row.filename,score:cosineSimilarity(queryVector,row.embedding)})).sort((a,b)=>b.score-a.score).slice(0,8); }
export async function runWorkflow({sessionId,mode,question}) { if(!openai) throw new Error('AI_LAB_NOT_CONFIGURED'); const passages=await retrieve(sessionId,question); const context=passages.map((p,i)=>`[${i+1}] ${p.filename}: ${p.content}`).join('\n\n'); const selected=mode==='career'?'career':'education'; const system=selected==='career'?'You are a grounded CV and cover-letter assistant. Use only the provided documents. Never invent experience. Cite claims as [1], [2].':'You are a grounded educational tutor. Use only the provided learning passages, explain at the learner level, and cite claims as [1], [2]. Say when sources do not answer.'; const completion=await openai.chat.completions.create({model:chatModel,temperature:0.2,max_tokens:800,messages:[{role:'system',content:system},{role:'user',content:`Question: ${String(question).slice(0,2000)}\n\nRetrieved sources:\n${context}`}]}); const answer=completion.choices?.[0]?.message?.content?.trim()||'No answer generated.'; const citations=[...answer.matchAll(/\[(\d+)\]/g)].map(m=>Number(m[1])).filter(n=>n>=1&&n<=passages.length); return {answer:{text:answer,citations:[...new Set(citations)],grounded:citations.length>0},passages,pipeline:pipelines[selected],agents:agents[selected].map((name,index)=>({name,status:'complete',note:index===1?`${passages.length} passages retrieved`:index===4?(citations.length?'Groundedness check passed':'Review required'):'Completed'}))}; }
