export const cvTemplates = [
  {
    id: 'ats-minimal',
    name: 'ATS Minimal',
    category: 'ATS',
    isAtsFriendly: true,
    componentKey: 'AtsMinimal',
  },
  {
    id: 'modern-sidebar',
    name: 'Modern Sidebar',
    category: 'Modern',
    isAtsFriendly: false,
    componentKey: 'ModernSidebar',
  },
  {
    id: 'bold-header',
    name: 'Bold Header',
    category: 'Modern',
    isAtsFriendly: true,
    componentKey: 'BoldHeader',
  },
  {
    id: 'elegant-serif',
    name: 'Elegant Serif',
    category: 'Classic',
    isAtsFriendly: true,
    componentKey: 'ElegantSerif',
  },
  {
    id: 'modern-teal',
    name: 'Modern Teal Two-Column',
    category: 'Modern',
    isAtsFriendly: true,
    componentKey: 'ModernTeal',
  },
  {
    id: 'modern-sidebar-blue',
    name: 'Modern Blue Sidebar',
    category: 'Modern',
    isAtsFriendly: true,
    componentKey: 'ModernSidebarBlue',
  },
  {
    id: 'ats-compact',
    name: 'Clean Compact ATS',
    category: 'ATS',
    isAtsFriendly: true,
    componentKey: 'AtsCompact',
  },
  {
    id: 'creative-timeline',
    name: 'Creative Timeline',
    category: 'Creative',
    isAtsFriendly: false,
    componentKey: 'CreativeTimeline',
  },
  {
    id: 'compact-one-pager',
    name: 'Compact One-Pager',
    category: 'Compact',
    isAtsFriendly: true,
    componentKey: 'CompactOnePager',
  },
];
