export const cvTemplates = [
  {
    id: 'ats-minimal',
    name: 'ATS Minimal',
    category: 'ATS',
    isAtsFriendly: true,
    componentKey: 'AtsMinimal',
  },
  {
    id: 'modern-sidebar',
    name: 'Modern Sidebar',
    category: 'Modern',
    isAtsFriendly: false,
    componentKey: 'ModernSidebar',
  },
  {
    id: 'bold-header',
    name: 'Bold Header',
    category: 'Modern',
    isAtsFriendly: true,
    componentKey: 'BoldHeader',
  },
  {
    id: 'elegant-serif',
    name: 'Elegant Serif',
    category: 'Classic',
    isAtsFriendly: true,
    componentKey: 'ElegantSerif',
  },
  {
    id: 'modern-teal',
    name: 'Modern Teal Two-Column',
    category: 'Modern',
    isAtsFriendly: true,
    componentKey: 'ModernTeal',
  },
  {
    id: 'modern-sidebar-blue',
    name: 'Modern Blue Sidebar',
    category: 'Modern',
    isAtsFriendly: true,
    componentKey: 'ModernSidebarBlue',
  },
  {
    id: 'ats-compact',
    name: 'Clean Compact ATS',
    category: 'ATS',
    isAtsFriendly: true,
    componentKey: 'AtsCompact',
  },
  {
    id: 'creative-timeline',
    name: 'Creative Timeline',
    category: 'Creative',
    isAtsFriendly: false,
    componentKey: 'CreativeTimeline',
  },
  {
    id: 'compact-one-pager',
    name: 'Compact One-Pager',
    category: 'Compact',
    isAtsFriendly: true,
    componentKey: 'CompactOnePager',
  },
  {
    id: 'executive-band',
    name: 'Executive Band',
    category: 'Executive',
    isAtsFriendly: true,
    componentKey: 'ExecutiveBand',
  },
  {
    id: 'skill-matrix',
    name: 'Skill Matrix',
    category: 'ATS',
    isAtsFriendly: true,
    componentKey: 'SkillMatrix',
  },
  {
    id: 'academic-compact',
    name: 'Academic Compact',
    category: 'Classic',
    isAtsFriendly: true,
    componentKey: 'AcademicCompact',
  },
  {
    id: 'project-forward',
    name: 'Project Forward',
    category: 'Modern',
    isAtsFriendly: true,
    componentKey: 'ProjectForward',
  },
  {
    id: 'operations-ledger',
    name: 'Operations Ledger',
    category: 'Professional',
    isAtsFriendly: true,
    componentKey: 'OperationsLedger',
  },
  {
    id: 'nairobi-grid',
    name: 'Nairobi Grid',
    category: 'Professional',
    isAtsFriendly: true,
    componentKey: 'NairobiGrid',
  },
  {
    id: 'diplomatic-classic',
    name: 'Diplomatic Classic',
    category: 'Classic',
    isAtsFriendly: true,
    componentKey: 'DiplomaticClassic',
  },
  {
    id: 'impact-sidebar',
    name: 'Impact Sidebar',
    category: 'Executive',
    isAtsFriendly: true,
    componentKey: 'ImpactSidebar',
  },
  {
    id: 'analyst-dashboard',
    name: 'Analyst Dashboard',
    category: 'Modern',
    isAtsFriendly: true,
    componentKey: 'AnalystDashboard',
  },
  {
    id: 'service-pro',
    name: 'Service Pro',
    category: 'Service',
    isAtsFriendly: true,
    componentKey: 'ServicePro',
  },
  {
    id: 'legal-formal',
    name: 'Legal Formal',
    category: 'Classic',
    isAtsFriendly: true,
    componentKey: 'LegalFormal',
  },
  {
    id: 'clinical-clean',
    name: 'Clinical Clean',
    category: 'Healthcare',
    isAtsFriendly: true,
    componentKey: 'ClinicalClean',
  },
  {
    id: 'portfolio-canvas',
    name: 'Portfolio Canvas',
    category: 'Creative',
    isAtsFriendly: true,
    componentKey: 'PortfolioCanvas',
  },
];
