export const defaultSectionOrder = ['summary','skills','experience','education','projects','certifications','extras'];
export const defaultSectionVisibility = defaultSectionOrder.reduce((a,k)=>(a[k]=true,a),{});
export const templateThemeDefaults={ 'modern-sidebar':{primary:'#0f172a',sidebarBg:'#0f172a',sidebarText:'#f8fafc',accent:'#38bdf8'}, 'bold-header':{primary:'#0f172a',headerBg:'#0f172a',headerText:'#ffffff',accent:'#38bdf8'}, 'modern-teal':{primary:'#0f766e',accent:'#0d9488',sectionBg:'#f0fdfa'}, 'modern-sidebar-blue':{primary:'#1d4ed8',sidebarBg:'#1d4ed8',sidebarText:'#eff6ff',accent:'#93c5fd'} };
const HEX_COLOR_RE=/^#([0-9a-f]{3}|[0-9a-f]{6})$/i;
export const esc=(v='')=>String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
export const safeKey = (s='') => String(s).trim().toLowerCase();
export function sanitizeRichTextHtml(input=''){const cleaned=String(input).replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,'').replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi,'');return cleaned.replace(/<\/?([a-z0-9-]+)([^>]*)>/gi,(full,rawTag,rawAttrs)=>{const tag=String(rawTag||'').toLowerCase();if(!['b','strong','i','em','u','span','br'].includes(tag)) return '';if(full.startsWith('</')) return `</${tag}>`;if(tag==='br') return '<br>';if(tag==='span'){const styleMatch=String(rawAttrs||'').match(/style\s*=\s*['\"]([^'\"]*)['\"]/i);const colorMatch=styleMatch?.[1]?.match(/color\s*:\s*([^;]+)/i);const color=colorMatch?.[1]?.trim();if(!color||!HEX_COLOR_RE.test(color)) return '<span>';return `<span style="color:${color}">`;}return `<${tag}>`;});}
export function normalizeCvDraft(draft={}){const templateDefaults=templateThemeDefaults[draft.templateId]||{};return {...draft,sectionOrder:draft.sectionOrder?.length?draft.sectionOrder:defaultSectionOrder,sectionVisibility:{...defaultSectionVisibility,...(draft.sectionVisibility||{})},basics:{...(draft.basics||{}),name:draft.basics?.name||'',headline:draft.basics?.headline||'',email:draft.basics?.email||'',phone:draft.basics?.phone||'',location:draft.basics?.location||'',links:draft.basics?.links||[],photoUrl:draft.basics?.photoUrl||''},summary:draft.summary||'',skills:draft.skills||[],experience:draft.experience||[],education:draft.education||[],projects:draft.projects||[],certifications:draft.certifications||[],extras:{languages:[],interests:[],...(draft.extras||{})},typography:{baseFontSize:12,h1Size:28,h2Size:12,h3Size:11,bodySize:11,fontFamily:'Inter, system-ui, Arial',...(draft.typography||{})},formatting:{textColor:'#0f172a',mutedTextColor:'#475569',linkColor:'#0f766e',...(draft.formatting||{})},templateTheme:{primary:'#0f172a',...templateDefaults,...(draft.templateTheme||{})},richText:{...(draft.richText||{})}};}
export const sectionVisible=(d,k)=>d.sectionVisibility?.[k]!==false;
export const buildCssVars=(d)=>`:root{--baseFontSize:${d.typography.baseFontSize}px;--h1Size:${d.typography.h1Size}px;--h2Size:${d.typography.h2Size}px;--h3Size:${d.typography.h3Size||11}px;--bodySize:${d.typography.bodySize||d.typography.baseFontSize}px;--fontFamily:${d.typography.fontFamily};--textColor:${d.formatting.textColor};--mutedTextColor:${d.formatting.mutedTextColor};--linkColor:${d.formatting.linkColor};--primary:${d.templateTheme.primary||'#0f172a'};--secondary:${d.templateTheme.secondary||'#1e293b'};--accent:${d.templateTheme.accent||d.templateTheme.primary||'#0f766e'};--sidebarBg:${d.templateTheme.sidebarBg||d.templateTheme.primary||'#0f172a'};--sidebarText:${d.templateTheme.sidebarText||'#f8fafc'};--headerBg:${d.templateTheme.headerBg||d.templateTheme.primary||'#0f172a'};--headerText:${d.templateTheme.headerText||'#ffffff'};--sectionBg:${d.templateTheme.sectionBg||'#f8fafc'};--borderColor:${d.templateTheme.borderColor||'#e2e8f0'}}`;
export const paginationCss = `@page{size:A4;margin:12mm}*{box-sizing:border-box}section,.item,.row,header,article{break-inside:avoid;page-break-inside:avoid}h2,h3{break-after:avoid;page-break-after:avoid}li{break-inside:avoid;page-break-inside:avoid}@media print{body{background:#fff}.page{margin:0 !important;box-shadow:none !important;width:auto !important;min-height:auto !important;overflow:visible}}`;
export const renderRichText = (draft, key, fallback='') => draft.richText?.[key]?.trim() ? sanitizeRichTextHtml(draft.richText[key]) : esc(fallback);
